### ISSUE TITLE
Maven plugin crashes when building peernetic on laptop

### ISSUE THREAD

**Issue by offbynull** [offbynull/coroutines#32]
Failed to execute goal com.offbynull.coroutines:maven-plugin:1.0.1:test-instrument (default) on project core: Unable to create instrumenter: IllegalStateException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.offbynull.coroutines:maven-plugin:1.0.1:test-instrument (default) on project core: Unable to create instrumenter
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to create instrumenter
	at com.offbynull.coroutines.mavenplugin.AbstractInstrumentMojo.getInstrumenter(AbstractInstrumentMojo.java:89)
	at com.offbynull.coroutines.mavenplugin.TestInstrumentMojo.execute(TestInstrumentMojo.java:71)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.IllegalStateException
	at com.offbynull.coroutines.instrumenter.asm.ClassInformationRepository.addClasspath(ClassInformationRepository.java:120)
	at com.offbynull.coroutines.instrumenter.asm.ClassInformationRepository.create(ClassInformationRepository.java:54)
	at com.offbynull.coroutines.instrumenter.Instrumenter.<init>(Instrumenter.java:140)
	at com.offbynull.coroutines.mavenplugin.AbstractInstrumentMojo.getInstrumenter(AbstractInstrumentMojo.java:87)
	... 22 more

**Comment by offbynull** [comment]
The reason for this is probably because the test-classes target folder doesn't exist.

C:\Users\user\Documents\NetBeansProjects\peernetic\core\target\test-classes <-- doesn't exit

As such, it'll crash because it can't find it. The plugin should not crash in this case, but just warn.
