### ISSUE TITLE
SimpleClassWriter.getCommonSuperClass argument may be set to string "null"

### ISSUE THREAD

**Issue by offbynull** [offbynull/coroutines#35]
"null" in this case isn't a type, but rather represents a type that isn't known yet?

```
Caused by: java.lang.IllegalArgumentException: No parent found for null (flattening null)
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)
	at com.offbynull.coroutines.instrumenter.asm.SimpleClassWriter.flattenHierarchy(SimpleClassWriter.java:102)
	at com.offbynull.coroutines.instrumenter.asm.SimpleClassWriter.getCommonSuperClass(SimpleClassWriter.java:78)
	at org.objectweb.asm.ClassWriter.getMergedType(ClassWriter.java:1654)
	at org.objectweb.asm.Frame.merge(Frame.java:1426)
	at org.objectweb.asm.Frame.merge(Frame.java:1325)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1475)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:834)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:726)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
	at com.offbynull.coroutines.instrumenter.Instrumenter.instrument(Instrumenter.java:223)
	at com.offbynull.coroutines.mavenplugin.AbstractInstrumentMojo.instrumentPath(AbstractInstrumentMojo.java:54)
	... 22 more
```

**Comment by offbynull** [comment]
Instrumenting C:\Users\User\Documents\NetBeansProjects\peernetic\examples\target\classes\com\offbynull\peernetic\examples\chord\RemoteRouteToTask.class

**Comment by offbynull** [comment]
Having the instrumenter just read and write the class without any modifications is fine. The instrumentation logic is causing this to break somewhere.

**Comment by offbynull** [comment]
Stopped crashing during instrumenter. Inspection of instrumented class shows the following suspect block:

```
mv.visitTypeInsn(CHECKCAST, "com/offbynull/peernetic/core/actor/Context");
mv.visitVarInsn(ASTORE, 2);
mv.visitVarInsn(ALOAD, 15);
mv.visitLdcInsn(new Integer(3));
mv.visitInsn(AALOAD);
mv.visitTypeInsn(CHECKCAST, "com/offbynull/peernetic/examples/chord/model/Pointer");
mv.visitVarInsn(ASTORE, 3);
mv.visitVarInsn(ALOAD, 15);
mv.visitLdcInsn(new Integer(5));
mv.visitInsn(AALOAD);
mv.visitTypeInsn(CHECKCAST, "null");
```

Last line may be trouble. Checkcast against object "null"? The issue may be in custom SimpleVerifier.
