### ISSUE TITLE
Encountered java.lang.ClassCastException during Continuation.suspend()

### ISSUE THREAD

**Issue by MrElusive** [offbynull/coroutines#52]
Hi Kasra,

First of all, thanks for a great library! I definitely prefer it over javaflow as the setup is much more straightforward to me.

My issue is that occasionally I will get a class cast exception on a call to Continuation.suspend() in LockeThread.join(). Clients will call LockeThread.join() when they want to wait on another thread to complete. Here is the code:
```java
	public void join(Continuation continuation, LockeThread threadToJoinOn) {
		if (!threadToJoinOn.isDone) {
			threadToJoinOn.joiningThreads.offer(this);
			SynchronizationOperation joinOperation = new SynchronizationOperation(Type.JOIN);

			continuation.setContext(joinOperation);
			continuation.suspend();
		}
	}
```

I'm pretty sure this is a multi-threading issue in my code since it happens intermittently. However, I was hoping I could get explanation about why this exception is occurring in the first place. Does the exception happen when Continuation.suspend() is first called, or does it happen when Continuation.suspend() returns? What conditions would cause this exception?
```
Exception in thread "Thread-0" com.offbynull.coroutines.user.CoroutineException: Exception thrown during execution
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:57)
	at main.java.edu.utexas.locke.LockeThread.execute(LockeThread.java:53)
	at main.java.edu.utexas.locke.LockeProcess.executeThread(LockeProcess.java:45)
	at main.java.edu.utexas.locke.LockeProcess.run(LockeProcess.java:34)
Caused by: java.lang.ClassCastException: test.java.edu.utexas.locke.LockeFibonacci cannot be cast to com.offbynull.coroutines.user.Continuation
	at main.java.edu.utexas.locke.LockeThread.join(LockeThread.java:42)
	at main.java.edu.utexas.locke.LockeTask.waitGet(LockeTask.java:18)
	at test.java.edu.utexas.locke.LockeFibonacci.compute(LockeFibonacci.java:23)
	at test.java.edu.utexas.locke.LockeFibonacci.compute(LockeFibonacci.java:23)
	at test.java.edu.utexas.locke.LockeFibonacci.compute(LockeFibonacci.java:8)
	at main.java.edu.utexas.locke.LockeTask.run(LockeTask.java:13)
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:54)
	... 3 more
```

Thanks,
Clayton

**Comment by offbynull** [comment]
Are you using 1.1.0?

**Comment by MrElusive** [comment]
Yes, it's 1.1.0.

One thought I had was this: is it possible that the threadToJoinOn parameter could have been garbage collected while the execution was suspended?  Would that cause this issue?

**Comment by MrElusive** [comment]
I should also mention that this exception does not affect the output and correctness of my program.

**Comment by MrElusive** [comment]
I found out what the problem was. I had a bug that was causing two threads to simultaneously execute the same coroutine. The coroutine was not happy about that. Anyway, everything runs perfectly now!
