### ISSUE TITLE
Enhancement: Add a class loader that will instrument classes as runtime

### ISSUE THREAD

**Issue by offbynull** [offbynull/coroutines#68]
Do this maybe. Use ClassLoaderClassInformationRepository instead of FileSystemClassinformationRepository.

**Comment by offbynull** [comment]
findResourceInternal

**Comment by offbynull** [comment]
This may no longer be as useful now that there's a Java Agent. But, it may still be useful for platforms that don't support Java Agents (e.g. Android)

**Comment by StephenSaturn** [comment]
Exception in thread "main" com.offbynull.coroutines.user.CoroutineException: Exception thrown during execution
0
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:69)
	at com.microsaturn.explorers.corouties.coroutines.Client.main(Client.java:9)
Caused by: java.lang.UnsupportedOperationException: Caller not instrumented
	at com.offbynull.coroutines.user.Continuation.suspend(Continuation.java:256)
	at com.microsaturn.explorers.corouties.coroutines.App.echo(App.java:30)
	at com.microsaturn.explorers.corouties.coroutines.App.run(App.java:24)
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:65)

**Comment by offbynull** [comment]
Not needed.
