### ISSUE TITLE
"if-else" instrumentation debug

### ISSUE THREAD

**Issue by little-pan** [offbynull/coroutines#84]
When I use coroutines in my co-nio [project](https://github.com/little-pan/co-nio) , an instrumentation debug occurs.
Version information, coroutines1.4.0 and JDK 1.8.
```
// io.conio.FactorialServerHandler.java
private boolean calc(Continuation co, CoChannel channel)throws IOException {
        buffer.clear();

        // Receive: From(4), To(4)
        for(;buffer.position() < 8;){
            final int i = channel.read(co, buffer);
            if(i == -1){
                return true;
            }
        }
        buffer.flip();
        final int from = buffer.getInt();
        final int to   = buffer.getInt();
        buffer.clear();

        ByteBuffer result;
        byte status = 0x0;
        if(from < 1 || to < 1 || from > to){
            final String error = String.format("[%d, %d] out of range", from, to);
            result = ByteBuffer.wrap(error.getBytes(encoding));
            status = 0x1;
        }else{
            // execute computation task in worker thread instead of in coroutine!
            final CoFuture<BigInteger> f = channel.execute(() -> {
                BigInteger factor = new BigInteger(from+"");
                for(int i = from + 1; i <= to; ++i){
                    factor = factor.multiply(new BigInteger(i+""));
                }
                return factor;
            });
            try {
                final BigInteger factor = f.get(co);
                result = ByteBuffer.wrap(factor.toString().getBytes(encoding));
            }catch(final ExecutionException e){
                final String error = e.getCause().getMessage();
                result = ByteBuffer.wrap(error.getBytes(encoding));
                status = 0x1;
            }
        }

        // Send: LEN(4), status, result
        buffer.putInt(result.capacity() + 1);
        buffer.put(status);
        buffer.flip();
        channel.write(co, buffer);  // line 85
        channel.write(co, result);
        return false;
    }
```
When the var "from" is 0 and "to" bigger than 0, processing logic enters "if" statement instead of "else" statement, but the exception thrown !

09:18:01.527 [serverCoGroup-nio] WARN  io.conio.CoHandler - Calc error
java.lang.ClassCastException: java.lang.String cannot be cast to io.conio.util.CoFuture
	at io.conio.FactorialServerHandler.calc(FactorialServerHandler.java:85) ~[classes/:na]
	at io.conio.FactorialServerHandler.handle(FactorialServerHandler.java:29) ~[classes/:na]
	at io.conio.PushCoChannel.run(PushCoChannel.java:27) [classes/:na]
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:65) [user-1.4.0.jar:na]
	at io.conio.CoChannel.resume(CoChannel.java:65) [classes/:na]
	at io.conio.CoGroup$NioGroup.handleWrite(CoGroup.java:533) [classes/:na]
	at io.conio.CoGroup$NioGroup.run(CoGroup.java:420) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by offbynull** [comment]
Do you have a standalone example that I can run? The error you're getting (ClassCastException) typically happens when there's a mismatch between the method logic and the saved stack data in the coroutine.

If you have a standalone example that I can use to replicate the issue, I'll be able to figure out what's happening.

**Comment by offbynull** [comment]
Okay, so I was able to load up your co-nio code and find the file you're referencing.

When I run the test with the latest coroutines version (1.5.0) on JDK10, it passes without error. There shouldn't be any instrumentation logic changes between 1.4.0 and 1.5.0. The difference between 1.4.0 and 1.5.0 was some small tweaks to get JDK9+ working.

What's possibly happening is that your compilation process is mangled -- some of your classes may not be getting instrumented, or are being recompiled without being instrumented, or may have been instrumented with an old version of the instrumenter, ... This happens sometimes when you use an IDE. Sometimes, when you make a change in an IDE, the IDE will try to optimize by compiling the changes directly instead of using the Gradle/Maven/Ant script. This ends up skipping the instrumentation process for that class.

This optimization trips me up all the time when I use NetBeans. I have to explicitly turn it off in every project I use coroutines in. I'm sure Eclipse and IntelliJ work similarly.

Double check that the IDE isn't causing the issue. If you can produce a standalone project that reproduces the issue even outside of an IDE, send it over so I can run it.

**Comment by little-pan** [comment]
Of course, the online test code in my github is passed. But the issue can happend in the following test case:
```
// io.conio.FactorialClientHandler.java
    @Override
    public void handle(Continuation co) {
        final CoChannel channel = (CoChannel)co.getContext();
        int i = 1;
        BigInteger result = null;
        try{
            final CoGroup group = channel.group();
            for(;!group.isShutdown(); ++i){
                **//result = calc(co, channel, 1, i);**
                result = calc(co, channel, 0, i); **// 1->0: the issue happends when processing logic enters "if" statement!!**
                final BigInteger expect;
                if(i <= FACTORS.length && result.compareTo(FACTORS[i - 1]) != 0){
                    log.warn("Result error: {} expect {}", result, FACTORS[i - 1]);
                    break;
                }
                ++times;
            }
        }catch (final IOException cause){
            log.warn("IO error", cause);
        }finally {
            //log.info("{}!: max-length = {}", i, maxlen);
            IoUtils.close(channel);
        }
    }
```

**Comment by offbynull** [comment]
I pasted your code into FactorialClientHandler and ran the tests multiple times, but they all still pass. Even when I downgrade from JDK10/1.5.0 to JDK8/1.4.0, they all still pass.

You're saying the issue only happens sometimes, right? I see you're launching a bunch of threads in your code. Could the issue you're experiencing be caused by a thread race condition? Are you missing some locks in your code?

**Comment by little-pan** [comment]
The ClassCastException always be thrown in the issue FactorialClientHandler test code, and all corotines in a co-nio group run in a single loop thread, different coroutines between groups communicates by socket.

**Comment by offbynull** [comment]
Okay, so I spent a bit more time investigating your code and the problems you mention are showing up, but those problems definitely look to be caused by thread concurrency issues in your code.  If you don't think this is the case, I need you to reproduce the problem as a small isolated single threaded standalone program, preferably no more than 2 or 3 Java files.

As a side note, the instrumentation process doesn't touch if-else branch points. The project has a pretty extensive set of tests and I've used it myself in several large non-trivial projects. I haven't had it produce bad instrumentation yet.

**Comment by little-pan** [comment]
@offbynull , you should run the TaskExecutionTest.java test case instead of the CoGroupTest.java.

**Comment by offbynull** [comment]
That is what I was running: TestExecutionTest.testNioTaskExection and TestExecutionTest.testAioTaskExection.

**Comment by little-pan** [comment]
This case looks like the issue #76? I will analyze and test it tomorrow.

**Comment by offbynull** [comment]
It isn't the same issue. Like I said, ...

1. I suspect the problem isn't with coroutines.
2. If it is, the best thing to do at this point is to create a simple
isolated example that reproduces the problem (no threads).

**Comment by little-pan** [comment]
Both only using "if" statement and merging "if" into the channel execute() method are OK:
```
    // io.conio.FactorialServerHandler.java
    private boolean calc(Continuation co, CoChannel channel)throws IOException {
        final FactorialRequest request;
        try {
            request = FactorialCodec.decodeRequest(co, buffer);
        }catch(final EOFException e){
            return true;
        }

        FactorialResponse response = null;
        // *ClassCastException thrown when processing enters the "if" statement and using "else", instrumentation bug?*
        if(request.from < 1 || request.to < 1 || request.from > request.to){
            final String error = String.format("[%d, %d] out of range", request.from, request.to);
            response = new FactorialResponse(error);
            FactorialCodec.encodeResponse(co, buffer, response);
            return false; // case-1: OK
        }

        // execute computation task in worker thread instead of in coroutine!
        final CoFuture<FactorialResponse> f = channel.execute(() -> {
            // Reserved test for instrumentation bug
            if(request.from < 1 || request.to < 1 || request.from > request.to){// case-2: OK
                final String error = String.format("[%d, %d] out of range", request.from, request.to);
                return new FactorialResponse(error);
            }
            BigInteger factor = new BigInteger(request.from+"");
            for(int i = request.from + 1; i <= request.to; ++i){
                factor = factor.multiply(new BigInteger(i+""));
            }
            return new FactorialResponse(factor);
        });

        try {
            response = f.get(co);
        }catch(final ExecutionException e){
            response = new FactorialResponse(e.getCause().getMessage());
        }
        FactorialCodec.encodeResponse(co, buffer, response);
        return false;
    }
```

**Comment by offbynull** [comment]
I've created a standalone class using your co-nio code and pasted it below. I used it with the changes you pasted in https://github.com/offbynull/coroutines/issues/84#issuecomment-413091171. Can you modify the standalone class to produce the problem you're experiencing?

If you can get it to happen using this non-threaded standalone class, it should be easy to identify what's happening.

If you can't, it's likely a problem with your code.

```java
package io.conio;

import com.offbynull.coroutines.user.Continuation;
import com.offbynull.coroutines.user.CoroutineRunner;
import java.io.IOException;
import java.nio.ByteBuffer;
import static java.nio.charset.StandardCharsets.US_ASCII;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    private static Logger LOG = LoggerFactory.getLogger(Main.class);
    
    private static int resultIdx;
    private static String[] results;
    
    public static void main(String[] args) {
        CoGroup coGroup = new CoGroup();
        CoChannel coChannel = new CoChannel(0, coGroup) {
            
            
            @Override
            public int read(Continuation co, ByteBuffer dst) throws IOException {
                if (resultIdx >= results.length) {
                    return -1;
                }
                
                byte[] resultBytes = results[resultIdx].getBytes(US_ASCII);
                dst.putInt(resultBytes.length + 1);
                dst.put((byte) 0);
                dst.put(resultBytes);
                
                resultIdx++;

                return dst.position();
            }
            
            @Override
            public int write(Continuation co, ByteBuffer src) throws IOException {
                // do nothing
                return 0;
            }
            
            @Override
            public boolean isOpen() {
                return true;
            }
            
            @Override
            public void close() {
                // do nothing
            }
        };
        FactorialClientHandler factorialClientHandler = new FactorialClientHandler();
        CoroutineRunner runner = new CoroutineRunner(c -> factorialClientHandler.handle(c));
        runner.setContext(coChannel);
        
        LOG.info("Start");
        
        resultIdx = 0;
        results = new String[] { "1", "2", "6", "24", "120", "720", "5040", "40320", "362880", "3628800", "39916800", "479001600" };
        runner.execute();
        
        resultIdx = 0;
        results = new String[] { "1", "2", "6", "24", "0", "0", "0"};
        runner.execute();
    }
}
```

**Comment by offbynull** [comment]
Please use the updated version of coroutines (1.5.1) to run the standalone class above. I just released it. It should be available on Maven Central in a few hours. You'll need to upgrade to Java9.

**Comment by little-pan** [comment]
If I move the "else" statement into a method and keep the "else" statement, this case also OK in coroutines 1.4.0 and 1.5.1.
eg.
```
protected boolean calc(Continuation co)throws IOException {
        final FactorialRequest request;
        try {
            request = FactorialCodec.decodeRequest(co, buffer);
        }catch(final EOFException e){
            return true;
        }

        FactorialResponse response = null;
        // *ClassCastException thrown when processing enters the "if" statement and using "else", instrumentation bug?*
        if(request.from < 1 || request.to < 1 || request.from > request.to){
            final String error = String.format("[%d, %d] out of range", request.from, request.to);
            response = new FactorialResponse(error);
            //FactorialCodec.encodeResponse(co, buffer, response);
            //return false;
        } else {
            response = doCalc(co, request); // also OK!
        }
        FactorialCodec.encodeResponse(co, buffer, response);
        return false;
    }

    protected FactorialResponse doCalc(Continuation co, final FactorialRequest request){
        log.debug("Calc begin: request {}", request);
        final CoChannel channel = (CoChannel)co.getContext();

        // execute computation task in worker thread instead of in coroutine!
        final CoFuture<FactorialResponse> f = channel.execute(() -> {
            // Reserved test for instrumentation bug
            if(request.from < 1 || request.to < 1 || request.from > request.to){
                final String error = String.format("[%d, %d] out of range", request.from, request.to);
                return new FactorialResponse(error);
            }
            BigInteger factor = new BigInteger(request.from+"");
            for(int i = request.from + 1; i <= request.to; ++i){
                factor = factor.multiply(new BigInteger(i+""));
            }
            return new FactorialResponse(factor);
        });

        try {
            log.debug("Calc: request {}", request);
            FactorialResponse response = f.get(co);
            log.debug("Calc end: factor {}", response.factor);
            return response;
        }catch(final ExecutionException e){
            log.warn("Calc error", e);
            return new FactorialResponse("Calc error");
        }
    }
```

**Comment by offbynull** [comment]
An update...

It looks like this is a problem with identifying a type on the local variable table. I'm not sure yet if this is a bug with my instrumentation logic or with ASM.

```
java.lang.ClassCastException: java.base/java.lang.String cannot be cast to io.conio.util.CoFuture
	at io.conio.FactorialServerHandler.calc(FactorialServerHandler.java:86)
	at io.conio.FactorialServerHandler.handle(FactorialServerHandler.java:29)
	at io.conio.PushCoChannel.run(PushCoChannel.java:27)
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:65)
	at io.conio.CoChannel.resume(CoChannel.java:69)
	at io.conio.CoGroup$NioGroup.handleWrite(CoGroup.java:483)
	at io.conio.CoGroup$NioGroup.run(CoGroup.java:370)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

```
Continuation Point ID: 2    Line: 86   Type: NormalInvokeContinuationPoint
  varObjects[0]        // LVT index is 0 / name is this / type is Lio/conio/FactorialServerHandler;
  varObjects[1]        // LVT index is 1 / name is co / type is Lcom/offbynull/coroutines/user/Continuation;
  varObjects[2]        // LVT index is 2 / name is channel / type is Lio/conio/CoChannel;
  varInts[0]           // LVT index is 3 / name is from / type is int
  varInts[1]           // LVT index is 4 / name is to / type is int
  varObjects[3]        // LVT index is 5 / name is result / type is Ljava/nio/ByteBuffer;
  varInts[2]           // LVT index is 6 / name is status / type is int
  varObjects[4]        // LVT index is 7 / name is ??????? / type is Lio/conio/util/CoFuture;    <-- it seems like this is the offending entry, more investigation required.
  operandObjects[0]    // operand index is 0 / type is Lio/conio/CoChannel;
  operandObjects[1]    // operand index is 1 / type is Lcom/offbynull/coroutines/user/Continuation;
  operandObjects[2]    // operand index is 2 / type is Ljava/nio/ByteBuffer;
```

**Comment by little-pan** [comment]
@offbynull First thank you very much.  Now I have solved this problem by breaking the "if-else" issue statement in io.conio.FactorialServerHandler.java.

Actually, my design is very simple：
1. Only coroutines run in the nio-or-aio single thread loop, includes suspend and resume operations.
2. Computation task and java aio pending task run in thread pools, and submit completed results to the nio-or-aio loop by java.util.concurrent.BlockingQueue.

**Comment by offbynull** [comment]
Thanks. I'll take a look at this shortly.

**Comment by offbynull** [comment]
Thank you for the standalone example. It was extremely helpful and isolated the bug. When I fix it, I'll make sure you get credit for both #84 and #85 in the readme and commit logs.

```java
if (!allInstrum) {
    final Long i = echo();
    System.out.println(" *** " + tag + ": " + i);
} else {
    final List<Integer> i = echo(c, 1);
    System.out.println(" *** " + tag + ": " + i);
}
echo(c, 2);
```

The problem here is that both "Long i" in the if block and "List<Integer> i" in the else block share the same LVT index (index=3).

Because the else block FLOWS into the last line (the if block JUMPS to it), the last line of code keeps the stackmap frame of the else block. That means that the stackmap frame for the last line identifies LVT index 3 as a "List<Integer>", when it could be either "List<Integer>" or "Long". Normally this wouldn't matter because LVT index 3 isn't used outside of the if-else block, but since coroutines tries to reload the all LVT items when you continue your coroutine, a ClassCastException will happen when the if block executes because a "Long" exists where a "List<Integer>" is expected.

Give me some time to think about how to fix this. I can try writing some code to do analysis and drop these unused items from coroutine storage. It should produce faster code that takes up less memory, but I don't exactly know how this analysis will work yet.

There may be other options as well. I need to think more about this.

Rest assured that I will fix this bug soon.

**Comment by little-pan** [comment]
@offbynull Hello. How is the issue fix going?

**Comment by offbynull** [comment]
I put in a question to the ASM mailing list to get clarification on how
some of the ASM classes related to this problem work. It may be a bug in
those classes or it may be that the classes don't work the way I thought
they did.

I'm digging around ASMs code right now. If there's nothing available and
the mailing list can't help, I'll start writing a custom solution.

**Comment by offbynull** [comment]
I have a fix in place. I'll release 1.5.2 tonight.

Once you confirm it's working I'll move the changes over to 1.4,x.

**Comment by offbynull** [comment]
1.5.2 has been released. It should hopefully be available on Maven central in the next few hours.

**Comment by little-pan** [comment]
@offbynull Thank you! I will test the fix.

**Comment by little-pan** [comment]
@offbynull OK. My all test cases pass in coroutines 1.5.2.

**Comment by offbynull** [comment]
1.4.2 has been released. It should hopefully be available on Maven central in the next few hours.
