### ISSUE TITLE
What can cause the issue "saving not allowed at this point"?

### ISSUE THREAD

**Issue by little-pan** [offbynull/coroutines#85]
My github [project](https://github.com/little-pan/co-nio) co-nio uses the coroutines library.
Version information: coroutines-1.4.0, JDK 1.8, windows 8.1.

// io.conio.FactorialProxyHandler.java in CoProxyTest
FAILED TO INSTRUMENT: java.lang.IllegalStateException: [Ljava/net/InetSocketAddress;
19:49:40.003 [proxyGroup-nio] WARN  io.conio.CoHandler - Calc error
java.lang.RuntimeException: Unexpected state (saving not allowed at this point)
	at io.conio.CoGroup$CoFutureImpl.get(CoGroup.java) ~[classes/:na]
	at io.conio.FactorialProxyHandler.doCalc(FactorialProxyHandler.java:38) ~[classes/:na]
	at io.conio.FactorialServerHandler.calc(FactorialServerHandler.java:55) ~[classes/:na]
	at io.conio.FactorialServerHandler.handle(FactorialServerHandler.java:26) ~[classes/:na]
	at io.conio.PushCoChannel.run(PushCoChannel.java:27) [classes/:na]
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:65) [user-1.4.0.jar:na]
	at io.conio.CoChannel.resume(CoChannel.java:65) [classes/:na]
	at io.conio.CoGroup$NioGroup.handleAcception(CoGroup.java:491) [classes/:na]
	at io.conio.CoGroup$NioGroup.run(CoGroup.java:415) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by offbynull** [comment]
There could be a couple of things going on here...

1. I think this is related to issue #84: the coroutine state isn't being synchronized across the threads it's being used in.

2. The following line in your output is an actual bug: FAILED TO INSTRUMENT: java.lang.IllegalStateException: [Ljava/net/InetSocketAddress; -- I've created a fix for it and pushed it into the repo. I'll cut a release soon.

If it's related to 2, it'll be fixed with the new release. If it's related to 1, it'll be fixed once we figure out what's happening with #84.

**Comment by little-pan** [comment]
@offbynull The issue has been fixed after coroutines library 1.4.0 upgraded to version 1.5.1.

**Comment by offbynull** [comment]
I can try it shouldn't be difficult. Did it also fix #84 or is #84 still
happening with 1.5.1?

**Comment by little-pan** [comment]
the issue #84 still is happening with coroutines 1.5.1.

**Comment by offbynull** [comment]
Let's get that resolved first and I'll backport this fix to 1.4.1.

Did you get a chance to look into my standalone program for #84? Were you
able to modify it to replicate the issue?

I'm going to spend some more time today investigating #84.

**Comment by offbynull** [comment]
I have a fix in place. All tests are passing (I've added your sample code as a unit test). I've also tested against my own projects that use coroutines and everything seems fine.

I'll release 1.5.2 tonight. Once you test it I'll cheerypick the changes and release 1.4.2.

I'll let you know once 1.5.2 is out.
